parameters:
    dwi_core.cache_factory.class: DWI\CoreBundle\Cache\CacheFactory
    dwi_core.result_cache.class: Doctrine\Common\Cache\CacheProvider

services:
    dwi_core.cache_factory:
        class: %dwi_core.cache_factory.class%
        arguments:
            em: '@doctrine.orm.entity_manager'

    dwi_core.result_cache:
        class: %dwi_core.result_cache.class%
        factory_service: dwi_core.cache_factory
        factory_method: getResultCache
