parameters:
#    dwi_core.example.class: DWI\CoreBundle\Example

services:
#    dwi_core.example:
#        class: %dwi_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
