parameters:
    dwi_core.gateway_cache_factory.class: DWI\CoreBundle\Gateway\Cache\GatewayCacheFactory
    dwi_core.gateway_result_cache.class: Doctrine\Common\Cache\CacheProvider

services:
    dwi_core.gateway_cache_factory:
        class: %dwi_core.gateway_cache_factory.class%
        arguments:
            em: '@doctrine.orm.entity_manager'

    dwi_core.gateway_result_cache:
        class: %dwi_core.gateway_result_cache.class%
        factory_service: dwi_core.gateway_cache_factory
        factory_method: getResultCache
