# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "misa_dev" do |box|
    box.vm.box     = "precise64"
    box.vm.box_url = "http://files.vagrantup.com/precise64.box"

    box.vm.network :private_network, ip: "192.168.56.101"
    # box.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
    # box.vm.network "forwarded_port", guest: 443, host: 4030, auto_correct: true

    box.vm.hostname = "misa.dev"

    box.vm.synced_folder "../src", "/var/www/src", nfs: true

    # Provisioners
    box.vm.provision :shell, :path => "pre-init.sh"

    box.vm.provision :puppet do |puppet|
      puppet.manifests_path = "puppet/manifests"
      puppet.manifest_file  = "vagrant.pp"
      puppet.module_path    = "modules"
      puppet.options        = "--verbose"
    end

    # box.vm.provision :shell, :path => "post-init.sh"
  end
end

