dwi_security_account_login:
    path: /account/login
    defaults: { _controller: DWISecurityBundle:Account:Login }

dwi_security_account_login_check:
    path: /account/login/check

dwi_security_account_logout:
    path: /account/logout
