parameters:
#    dwi_contact.example.class: DWI\ContactBundle\Example

services:
#    dwi_contact.example:
#        class: %dwi_contact.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
