parameters:
    dwi_contact.con_var_gateway.class: DWI\ContactBundle\Gateway\ConVarGateway

services:
    dwi_contact.con_var_gateway:
        class: %dwi_contact.con_var_gateway.class%
        arguments:
            conn: '@doctrine.dbal.default_connection'
            cache: '@dwi_core.result_cache'
