dwi_static_homepage:
    pattern:  /
    defaults: { _controller: DWIStaticBundle:Static:home }
    methods: [GET]

dwi_static_about:
    pattern:  /about
    defaults: { _controller: DWIStaticBundle:Static:about }
    methods: [GET]

dwi_static_about_settings:
    pattern:  /admin/about
    defaults: { _controller: DWIStaticBundle:StaticAdmin:about }
    methods: [GET,POST]
