parameters:
#    dwi_static.example.class: DWI\StaticBundle\Example

services:
#    dwi_static.example:
#        class: %dwi_static.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
