parameters:
    dwi_static.static_home_presenter.class: DWI\StaticBundle\View\Presenter\HomePresenter

services:
    dwi_static.static_home_presenter:
        class: %dwi_static.static_home_presenter.class%
