dwi_portfolio_homepage:
    pattern:  /portfolio/{page}
    defaults: { _controller: DWIPortfolioBundle:Portfolio:portfolio, page: 1 }
    methods:  [GET]
    requirements:
        page: \d+

dwi_portfolio_gallery:
    pattern: /portfolio/gallery/{id}
    defaults: { _controller: DWIPortfolioBundle:Portfolio:gallery }
    methods: [GET]
    requirements:
        id: \d+

dwi_portfolio_create_gallery:
    pattern: /portfolio/gallery/create
    defaults: { _controller: DWIPortfolioBundle:Portfolio:createGallery }
    methods: [GET,POST]

dwi_portfolio_remove_gallery:
    pattern: /portfolio/gallery/{id}/remove
    defaults: { _controller: DWIPortfolioBundle:Portfolio:deleteGallery }
    methods: [GET,POST]
    requirements:
        id: \d+
