dwi_portfolio_homepage:
    pattern:  /portfolio/{page}
    defaults: { _controller: DWIPortfolioBundle:Portfolio:view, page: 1 }
    methods:  [GET]
    requirements:
        page: \d+

dwi_portfolio_view_tag:
    pattern:  /portfolio/tag/{id}/{page}
    defaults: { _controller: DWIPortfolioBundle:Portfolio:viewTag, page: 1 }
    methods:  [GET]
    requirements:
        id: \d+
        page: \d+

dwi_portfolio_gallery:
    pattern: /portfolio/gallery/{id}
    defaults: { _controller: DWIPortfolioBundle:Gallery:gallery }
    methods: [GET]
    requirements:
        id: \d+

dwi_portfolio_manage_galleries:
    pattern: /admin/portfolio/galleries/{page}
    defaults: { _controller: DWIPortfolioBundle:PortfolioAdmin:galleries, page: 1 }
    methods: [GET]
    requirements:
        page: \d+

dwi_portfolio_manage_tags:
    pattern: /admin/portfolio/tags
    defaults: { _controller: DWIPortfolioBundle:PortfolioAdmin:tags }
    methods: [GET]

dwi_portfolio_manage_gallery:
    pattern: /admin/portfolio/gallery/{id}
    defaults: { _controller: DWIPortfolioBundle:GalleryAdmin:view }
    methods: [GET]
    requirements:
        id: \d+

dwi_portfolio_gallery_sort_images:
    pattern: /admin/portfolio/gallery/{id}/images/sort
    defaults: { _controller: DWIPortfolioBundle:GalleryAdmin:sort }
    methods: [GET, POST]
    requirements:
        id: \d+

dwi_portfolio_swap_display_order:
    pattern: /admin/portfolio/gallery/manage/{id}/image/swap-display-order/{from}/{to}
    defaults: { _controller: DWIPortfolioBundle:Image:swapDisplayOrder }
    methods: [GET]
    requirements:
        id: \d+
        from: \d+
        to: \d+

dwi_portfolio_create_tag:
    pattern: /admin/portfolio/tag/create
    defaults: { _controller: DWIPortfolioBundle:TagAdmin:create }
    methods: [GET,POST]

dwi_portfolio_edit_tag:
    pattern: /admin/portfolio/tag/{id}/edit
    defaults: { _controller: DWIPortfolioBundle:TagAdmin:edit }
    methods: [GET,POST]
    requirements:
        id: \d+

dwi_portfolio_remove_tag:
    pattern: /admin/portfolio/tag/{id}/remove
    defaults: { _controller: DWIPortfolioBundle:TagAdmin:delete }
    methods: [GET,POST]
    requirements:
        id: \d+

dwi_portfolio_create_gallery:
    pattern: /admin/portfolio/gallery/create
    defaults: { _controller: DWIPortfolioBundle:Gallery:createGallery }
    methods: [GET,POST]

dwi_portfolio_edit_gallery:
    pattern: /admin/portfolio/gallery/{id}/edit
    defaults: { _controller: DWIPortfolioBundle:Gallery:editGallery }
    methods: [GET,POST]
    requirements:
        id: \d+

dwi_portfolio_remove_gallery:
    pattern: /admin/portfolio/gallery/{id}/remove
    defaults: { _controller: DWIPortfolioBundle:Gallery:deleteGallery }
    methods: [GET,POST]
    requirements:
        id: \d+

dwi_portfolio_set_cover_gallery:
    pattern: /admin/portfolio/gallery/{id}/setcover/{imageId}
    defaults: { _controller: DWIPortfolioBundle:Gallery:setCover }
    methods: [GET,POST]
    requirements:
        id: \d+
        imageId: \d+

dwi_portfolio_publish_gallery:
    pattern: /admin/portfolio/gallery/{id}/publish
    defaults: { _controller: DWIPortfolioBundle:Gallery:publishGallery }
    methods: [GET,POST]
    requirements:
        id: \d+

dwi_portfolio_upload_images_form:
    pattern: /admin/portfolio/gallery/{id}/image/upload
    defaults: { _controller: DWIPortfolioBundle:Image:uploadImagesForm }
    methods: [GET,POST]
    requirements:
        id: \d+

dwi_portfolio_upload_image:
    pattern: /admin/portfolio/gallery/{id}/image/upload/process
    defaults: { _controller: DWIPortfolioBundle:Image:uploadImage }
    requirements:
        id: \d+

dwi_portfolio_edit_image_description:
    pattern: /admin/portfolio/gallery/{galleryId}/image/{id}/edit-description
    defaults: { _controller: DWIPortfolioBundle:Image:editDescription }
    methods: [GET,POST]
    requirements:
        galleryId: \d+
        id: \d+

dwi_portfolio_remove_image:
    pattern: /admin/portfolio/gallery/{galleryId}/image/{id}/remove
    defaults: { _controller: DWIPortfolioBundle:Image:deleteImage }
    methods: [GET,POST]
    requirements:
        galleryId: \d+
        id: \d+
