parameters:
#    dwi_portfolio.example.class: DWI\PortfolioBundle\Example

services:
#    dwi_portfolio.example:
#        class: %dwi_portfolio.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
