parameters:
    dwi_portfolio.gallery_manager.class: DWI\PortfolioBundle\Entity\GalleryManager

services:
    dwi_portfolio.gallery_manager:
        class: %dwi_portfolio.gallery_manager.class%
        arguments:
            em: "@doctrine.orm.entity_manager"
