parameters:
    dwi_portfolio.gallery_mediator.class: DWI\PortfolioBundle\Mediator\GalleryMediator

services:
    dwi_portfolio.gallery_mediator:
        class: %dwi_portfolio.gallery_mediator.class%
        arguments:
            em: "@doctrine.orm.entity_manager"
