parameters:
    # Repositories
    dwi_portfolio.gallery_repository.class: Doctrine\ORM\EntityRepository
    dwi_portfolio.gallery_entity: "DWIPortfolioBundle:Gallery"
    dwi_portfolio.gallery_view_repository.class: Doctrine\ORM\EntityRepository
    dwi_portfolio.gallery_view_entity: "DWIPortfolioBundle:GalleryView"
    dwi_portfolio.image_repository.class: Doctrine\ORM\EntityRepository
    dwi_portfolio.image_entity: "DWIPortfolioBundle:Image"
    dwi_portfolio.tag_repository.class: Doctrine\ORM\EntityRepository
    dwi_portfolio.tag_entity: "DWIPortfolioBundle:Tag"

    # Gateways
    dwi_portfolio.gallery_gateway.class: DWI\PortfolioBundle\Gateway\GalleryGateway
    dwi_portfolio.gallery_view_gateway.class: DWI\PortfolioBundle\Gateway\GalleryViewGateway
    dwi_portfolio.image_gateway.class: DWI\PortfolioBundle\Gateway\ImageGateway

    # Forms
    dwi_portfolio.create_gallery_form_factory.class: DWI\PortfolioBundle\Form\Factory\GalleryFormFactory
    dwi_portfolio.create_gallery_form.class: Symfony\Component\Form\Form
    dwi_portfolio.upload_image_form_factory.class: DWI\PortfolioBundle\Form\Factory\ImageFormFactory
    dwi_portfolio.upload_image_form.class: Symfony\Component\Form\Form

    # Presenters
    dwi_portfolio.portfolio_view_presenter.class: DWI\PortfolioBundle\View\Presenter\Portfolio\ViewPresenter
    dwi_portfolio.portfolio_view_tag_presenter.class: DWI\PortfolioBundle\View\Presenter\Portfolio\ViewTagPresenter
    dwi_portfolio.portfolio_manage_presenter.class: DWI\PortfolioBundle\View\Presenter\Portfolio\ManagePresenter
    dwi_portfolio.gallery_presenter.class: DWI\PortfolioBundle\View\Presenter\Gallery\GalleryPresenter
    dwi_portfolio.gallery_manage_presenter.class: DWI\PortfolioBundle\View\Presenter\Gallery\ManagePresenter
    dwi_portfolio.gallery_set_cover_presenter.class: DWI\PortfolioBundle\View\Presenter\Gallery\SetCoverPresenter
    dwi_portfolio.image_delete_presenter.class: DWI\PortfolioBundle\View\Presenter\Image\DeletePresenter
    dwi_portfolio.image_edit_description_presenter.class: DWI\PortfolioBundle\View\Presenter\Image\EditDescriptionPresenter
    dwi_portfolio.image_upload_presenter.class: DWI\PortfolioBundle\View\Presenter\Image\UploadPresenter

services:
    dwi_portfolio.gallery_repository:
        class: %dwi_portfolio.gallery_repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            em: %dwi_portfolio.gallery_entity%

    dwi_portfolio.gallery_view_repository:
        class: %dwi_portfolio.gallery_view_repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            em: %dwi_portfolio.gallery_view_entity%

    dwi_portfolio.image_repository:
        class: %dwi_portfolio.image_repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            em: %dwi_portfolio.image_entity%

    dwi_portfolio.tag_repository:
        class: %dwi_portfolio.image_repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            em: %dwi_portfolio.tag_entity%

    dwi_portfolio.gallery_gateway:
        class: %dwi_portfolio.gallery_gateway.class%
        arguments:
            conn: '@doctrine.dbal.default_connection'
            cache: '@dwi_core.result_cache'

    dwi_portfolio.gallery_view_gateway:
        class: %dwi_portfolio.gallery_view_gateway.class%
        arguments:
            conn: '@doctrine.dbal.default_connection'
            cache: '@dwi_core.result_cache'

    dwi_portfolio.image_gateway:
        class: %dwi_portfolio.image_gateway.class%
        arguments:
            conn: '@doctrine.dbal.default_connection'
            cache: '@dwi_core.result_cache'

    dwi_portfolio.create_gallery_form_factory:
        class: %dwi_portfolio.create_gallery_form_factory.class%
        scope: "request"
        arguments:
            ff: "@form.factory"
            generator: "@router"

    dwi_portfolio.create_gallery_form:
        class: %dwi_portfolio.create_gallery_form.class%
        factory_service: dwi_portfolio.create_gallery_form_factory
        factory_method: prepareForm

    dwi_portfolio.upload_image_form_factory:
        class: %dwi_portfolio.upload_image_form_factory.class%
        scope: "request"
        arguments:
            ff: "@form.factory"
            generator: "@router"

    dwi_portfolio.upload_image_form:
        class: %dwi_portfolio.upload_image_form.class%
        factory_service: dwi_portfolio.upload_image_form_factory
        factory_method: prepareForm

    dwi_portfolio.portfolio_view_presenter:
        class: %dwi_portfolio.portfolio_view_presenter.class%

    dwi_portfolio.portfolio_view_tag_presenter:
        class: %dwi_portfolio.portfolio_view_tag_presenter.class%

    dwi_portfolio.portfolio_manage_presenter:
        class: %dwi_portfolio.portfolio_manage_presenter.class%

    dwi_portfolio.gallery_presenter:
        class: %dwi_portfolio.gallery_presenter.class%

    dwi_portfolio.gallery_manage_presenter:
        class: %dwi_portfolio.gallery_manage_presenter.class%

    dwi_portfolio.gallery_set_cover_presenter:
        class: %dwi_portfolio.gallery_set_cover_presenter.class%

    dwi_portfolio.image_delete_presenter:
        class: %dwi_portfolio.image_delete_presenter.class%

    dwi_portfolio.image_edit_description_presenter:
        class: %dwi_portfolio.image_edit_description_presenter.class%

    dwi_portfolio.image_upload_presenter:
        class: %dwi_portfolio.image_upload_presenter.class%
