dwi_security:
    resource: "@DWISecurityBundle/Resources/config/routing.yml"
    prefix:   /

dwi_core:
    resource: "@DWICoreBundle/Resources/config/routing.yml"
    prefix:   /

dwi_portfolio:
    resource: "@DWIPortfolioBundle/Resources/config/routing.yml"
    prefix:   /

dwi_contact:
    resource: "@DWIContactBundle/Resources/config/routing.yml"
    prefix:   /

dwi_asset:
    resource: "@DWIAssetBundle/Resources/config/routing.yml"
    prefix:   /

dwi_static:
    resource: "@DWIStaticBundle/Resources/config/routing.yml"
    prefix:   /

_imagine:
    resource: .
    type:     imagine
