security:
    encoders:
        DWI\SecurityBundle\Entity\User:
            algorithm: bcrypt
            cost: 15

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        default:
            entity: { class: DWI\SecurityBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/account/login$
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: /account/login/check
                login_path: /account/login
            logout:
                path:   /account/logout
                target: /portfolio
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/account/login }
        - { path: ^/admin, roles: ROLE_ADMIN }
